# Generated by Django 6.0 on 2026-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_subjects_discount_percent_subjects_package_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Скидка %', max_length=40, verbose_name='Discount'),
        ),
    ]
