# Generated by Django 6.0 on 2026-01-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_subjects_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='discount_percent',
            field=models.IntegerField(help_text='Скидка %', max_length=40, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='package_size',
            field=models.IntegerField(default=10, max_length=40),
        ),
    ]
