# Generated by Django 6.0 on 2026-01-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='cost',
            field=models.IntegerField(max_length=40),
        ),
    ]
