# Generated by Django 6.0 on 2026-01-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_subjects_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='%', max_length=40, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='package_size',
            field=models.IntegerField(default=0, max_length=40),
        ),
    ]
